### PR TITLE
fix opencv issues

### PR DESCRIPTION
**Pull request by lindemeier**

### CODE REVIEW

**Comment by fmessmer** [comment]
@lindemeier thanks...but could you undo the formatting changes?

**Comment by lindemeier** [comment]
> @lindemeier thanks...but could you undo the formatting changes?

Whoops sry, yes my formatter messed up ... again.
It is supposed to only format changed lines, a new feature of vscode. I guess it's not working properly.

It would be great if we could commit to a  formatting to increase readability, reduce style commits, have a common format and avoid things like this.

**Comment by lindemeier** [comment]
> @lindemeier thanks...but could you undo the formatting changes?

done.

Removed the deprecated dynamic exception specifications as well

**Comment by fmessmer** [comment]
thanks...

**Pull request merged**
